# Build and deploy the site.
# This assumes that CI was green before `dev` was merged in `master`

name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GH Pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: build
          committer_name: shabados-bot
          commiter_email: team@shabados.com
          keep_history: true
          allow_empty_commit: false
          fqdn: docs.shabados.com
        env:
          GITHUB_PAT: ${{ secrets.GH_BOT_TOKEN }}
